'use strict';
(()=>{
 const el=id=>document.getElementById(id),uid=()=>crypto.randomUUID();let groupId=null,templateId=null;
 const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
 const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const button=(text,fn)=>{const b=node('button',text);b.type='button';b.addEventListener('click',fn);return b;};
 const status=(id,text)=>el(id).textContent=text;
 const run=(id,fn)=>{try{fn();}catch(e){status(id,e.message);}};
 function select(id,items,placeholder){const input=el(id),current=input.value;input.replaceChildren();for(const [value,label] of [["",placeholder],...items]){const o=node('option',label);o.value=value;input.append(o);}if(items.some(([v])=>v===current))input.value=current;}
 function selectors(){const d=VXTLocal.snapshot();for(const id of ['team-group','block-group'])select(id,(d.trainingGroups||[]).map(g=>[g.id,g.name]),'Choose group');select('team-template',(d.workoutTemplates||[]).map(t=>[t.id,t.name]),'Choose template');}
 function checkRoster(id,ids=[]){el(id).replaceChildren();for(const a of VXTLocal.snapshot().athletes){const label=node('label');label.className='check';const input=node('input');input.type='checkbox';input.value=a.id;input.checked=ids.includes(a.id);label.append(input,document.createTextNode(a.name));el(id).append(label);}}
 const checked=id=>[...el(id).querySelectorAll('input:checked')].map(i=>i.value);
 function confirmDelete(parent,label,fn){const box=node('div');box.hidden=true;box.append(node('p',label+'? Existing workouts and results will be kept.'),button('Confirm deletion',fn),button('Cancel',()=>box.hidden=true));parent.append(button('Delete',()=>box.hidden=false),box);}
 function groups(){const d=VXTLocal.snapshot();el('group-list').replaceChildren();for(const g of d.trainingGroups||[]){const card=node('div');card.className='session-summary';card.append(node('h3',g.name),node('p',g.athleteIds.map(id=>d.athletes.find(a=>a.id===id)?.name).join(', ')||'No current members'),button('Edit '+g.name,()=>{groupId=g.id;el('group-name').value=g.name;checkRoster('group-athletes',g.athleteIds);el('group-cancel').hidden=false;}));confirmDelete(card,'Delete group '+g.name,()=>run('group-status',()=>{VXTLocal.appendReviewed(VXTCoaching.remove(VXTLocal.snapshot(),'trainingGroups',g.id));resetGroup();groups();selectors();status('group-status','Group deleted.');}));el('group-list').append(card);}if(!d.trainingGroups?.length)el('group-list').append(node('p','No groups saved yet.'));}
 function resetGroup(){groupId=null;el('group-form').reset();el('group-cancel').hidden=true;checkRoster('group-athletes');}
 el('group-cancel').addEventListener('click',resetGroup);
 el('group-form').addEventListener('submit',e=>{e.preventDefault();run('group-status',()=>{VXTLocal.appendReviewed(VXTCoaching.saveGroup(VXTLocal.snapshot(),{id:groupId,name:el('group-name').value,athleteIds:checked('group-athletes')},uid));resetGroup();groups();selectors();status('group-status','Group saved. Use it in Team training or Training blocks.');});});
 for(const [prefix,container] of [['team','team-athletes'],['block','block-athletes']])el(prefix==='team'?'team-add-group':'block-add-group').addEventListener('click',()=>run(prefix==='team'?'team-status':'block-status',()=>{const g=VXTLocal.snapshot().trainingGroups?.find(g=>g.id===el(prefix+'-group').value);if(!g)throw Error('Choose a group first.');for(const input of el(container).querySelectorAll('input'))if(g.athleteIds.includes(input.value))input.checked=true;el(container).querySelector('input')?.dispatchEvent(new Event('change',{bubbles:true}));status(prefix==='team'?'team-status':'block-status','Group athletes selected. Review before saving.');}));
 function resetTemplate(){templateId=null;el('template-form').reset();el('template-event').value='60m';el('template-cancel').hidden=true;}
 function templates(){const d=VXTLocal.snapshot();el('template-list').replaceChildren();for(const t of d.workoutTemplates||[]){const card=node('div');card.className='session-summary';card.append(node('h3',t.name),node('p',t.workout),node('p',t.reps+' rep entries · '+t.event+(t.restAfter===null?'':' · '+t.restAfter+'s rest')),button('Use '+t.name,()=>{document.querySelector('[data-tab="team"]').click();document.dispatchEvent(new CustomEvent('vxt-use-template',{detail:t.id}));}),button('Edit '+t.name,()=>{templateId=t.id;for(const [id,key] of [['name','name'],['workout','workout'],['event','event'],['reps','reps'],['rest','restAfter'],['notes','notes']])el('template-'+id).value=t[key]??'';el('template-cancel').hidden=false;}));confirmDelete(card,'Delete template '+t.name,()=>run('template-status',()=>{VXTLocal.appendReviewed(VXTCoaching.remove(VXTLocal.snapshot(),'workoutTemplates',t.id));resetTemplate();templates();selectors();status('template-status','Template deleted.');}));el('template-list').append(card);}if(!d.workoutTemplates?.length)el('template-list').append(node('p','No templates saved yet. You can also save any assigned team workout as a template.'));}
 for(const event of VXTSessions.events){const o=node('option',event);o.value=event;el('template-event').append(o);}el('template-event').value='60m';
 el('template-cancel').addEventListener('click',resetTemplate);
 el('template-form').addEventListener('submit',e=>{e.preventDefault();run('template-status',()=>{VXTLocal.appendReviewed(VXTCoaching.saveTemplate(VXTLocal.snapshot(),{id:templateId,name:el('template-name').value,workout:el('template-workout').value,event:el('template-event').value,reps:el('template-reps').value,restAfter:el('template-rest').value,notes:el('template-notes').value},uid));resetTemplate();templates();selectors();status('template-status','Template saved.');});});
 el('team-use-template').addEventListener('click',()=>document.dispatchEvent(new CustomEvent('vxt-use-template',{detail:el('team-template').value})));
 function control(parent,label,type,value,options=[]){const wrap=node('label',label),input=node(type==='select'?'select':type==='textarea'?'textarea':'input');if(!['select','textarea'].includes(type))input.type=type;for(const option of options){const o=node('option',option);o.value=option;input.append(o);}input.value=value??'';wrap.append(input);parent.append(wrap);return input;}
 function checkin(parent,w,a,refresh){const d=VXTLocal.snapshot(),name=d.athletes.find(x=>x.id===a.athleteId)?.name||'Athlete';const details=node('details');details.className='athlete-checkin';details.append(node('summary',name+' · Targets & readiness · '+(a.attendance||'Unrecorded')));const form=node('form');
  const target=control(form,'Target times / instructions — '+name,'textarea',a.target);target.maxLength=500;target.placeholder='Example: 3 × 150m in 21–22 seconds';
  const attendance=control(form,'Attendance — '+name,'select',a.attendance||'Unrecorded',['Unrecorded','Present','Absent','Modified']);
  const fields=node('div');fields.className='fields';form.append(fields);const energy=control(fields,'Energy (1 low–5 high) — '+name,'number',a.energy);energy.min='1';energy.max='5';energy.step='1';const soreness=control(fields,'Soreness (0 none–10 high) — '+name,'number',a.soreness);soreness.min='0';soreness.max='10';soreness.step='1';const notes=control(form,'Readiness / modification notes — '+name,'textarea',a.readinessNotes);notes.maxLength=1000;
  const save=node('button','Save check-in for '+name);save.type='submit';const feedback=node('p');feedback.setAttribute('role','status');form.append(save,feedback);form.addEventListener('submit',e=>{e.preventDefault();try{VXTLocal.appendReviewed(VXTCoaching.saveCheckin(VXTLocal.snapshot(),w.id,a.athleteId,{target:target.value,attendance:attendance.value,energy:energy.value,soreness:soreness.value,readinessNotes:notes.value}));refresh();status('team-status','Targets and check-in saved for '+name+'.');}catch(e){feedback.textContent=e.message;}});details.append(form);parent.append(details);
 }
 globalThis.VXTCoachingUI={checkin};
 function calendar(){run('calendar-status',()=>{const d=VXTLocal.snapshot();select('calendar-athlete',d.athletes.map(a=>[a.id,a.name]),'All athletes');const week=VXTCoaching.week(d,el('calendar-date').value,el('calendar-athlete').value);el('calendar-range').textContent=VXT.formatDate(week[0].date)+' – '+VXT.formatDate(week[6].date);el('calendar-days').replaceChildren();for(const day of week){const card=node('section');card.className='calendar-day';card.append(node('h3',new Date(day.date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'})+' · '+VXT.formatDate(day.date)));
   for(const w of day.workouts){const row=node('div');row.className='calendar-entry';row.append(node('strong',VXT.formatStartTime(w.startTime)+' · '+w.name),node('p',w.assignments.length+' assigned · '+w.assignments.filter(a=>a.completed).length+' completed'));const linked=day.sessions.filter(s=>s.sourceWorkoutId===w.id);if(linked.length)row.append(node('p',linked.length+' linked result session(s)'));const c=day.conflicts.find(c=>c.id===w.id);if(c)row.append(node('p','Possible conflicts: '+c.athletes.map(c=>d.athletes.find(a=>a.id===c.athleteId)?.name).join(', ')));row.append(button('Open workout '+w.name,()=>{document.querySelector('[data-tab="team"]').click();const section=[...el('team-history').children].find(x=>x.dataset.workoutId===w.id);if(section){section.open=true;section.scrollIntoView({block:'center'});}}));card.append(row);}
   for(const s of day.sessions.filter(s=>!s.sourceWorkoutId)){const row=node('div');row.className='calendar-entry';row.append(node('strong',VXT.formatStartTime(s.startTime)+' · Logged: '+s.name),button('Open session '+s.name,()=>{document.querySelector('[data-tab="sessions"]').click();const section=[...el('session-history').children].find(x=>x.dataset.sessionId===s.id);if(section){section.open=true;section.scrollIntoView({block:'center'});}}));const ids=[...new Set((s.efforts||d.results.filter(r=>r.sessionId===s.id)).map(e=>e.athleteId))];const conflicts=VXT.schedulingConflicts(d,{date:day.date,excludeSessionId:s.id,athleteIds:ids});if(conflicts.length)row.append(node('p','Possible conflicts: '+conflicts.map(c=>d.athletes.find(a=>a.id===c.athleteId)?.name).join(', ')));card.append(row);}
   for(const b of day.blocks){const w=Math.floor((new Date(day.date+'T12:00:00Z')-new Date(b.startDate+'T12:00:00Z'))/604800000)+1;card.append(node('p','Block: '+b.name+' · Week '+w+' · '+(b.plan[w-1]?.focus||'Focus not set')));}if(!day.workouts.length&&!day.sessions.length&&!day.blocks.length)card.append(node('p','No training planned or logged.'));el('calendar-days').append(card);}status('calendar-status','');});}
 el('calendar-date').value=today();el('calendar-date').addEventListener('change',calendar);el('calendar-athlete').addEventListener('change',calendar);for(const [id,days] of [['calendar-prev',-7],['calendar-next',7]])el(id).addEventListener('click',()=>{el('calendar-date').value=VXTBlocks.addDays(el('calendar-date').value||today(),days);calendar();});el('calendar-today').addEventListener('click',()=>{el('calendar-date').value=today();calendar();});
 function table(headers,rows){const t=node('table'),head=node('thead'),tr=node('tr');for(const h of headers)tr.append(node('th',h));head.append(tr);t.append(head);const body=node('tbody');for(const values of rows){const row=node('tr');for(const value of values)row.append(node('td',String(value)));body.append(row);}t.append(body);const wrap=node('div');wrap.className='table-wrap';wrap.append(t);return wrap;}
 function report(loadNotes=false){run('report-status',()=>{const d=VXTLocal.snapshot();select('report-athlete',d.athletes.map(a=>[a.id,a.name]),'Choose athlete');if(!el('report-athlete').value)el('report-athlete').value=el('active-athlete').value;const id=el('report-athlete').value,a=d.athletes.find(a=>a.id===id),body=el('report-content');body.replaceChildren();if(!a){body.append(node('p','Add or select an athlete first.'));return;}if(loadNotes)el('report-notes').value=d.athleteReports?.find(r=>r.athleteId===id)?.notes||'';
 body.append(node('p','VXT PERFORMANCE / HEMPHILL PERFORMANCE REPORT'),node('h2',a.name),node('p','Generated '+VXT.formatDate(today())),node('h3','Personal bests & progress'));
 const rows=VXTCoaching.progress(d,id);if(!rows.length)body.append(node('p','No measured results yet.'));else body.append(table(['Event / timing','Personal best','First dated best','Latest dated best','Improvement'],rows.map(r=>[r.label,r.best.time.toFixed(2)+'s · '+VXT.formatDate(r.best.date),r.first?r.first.time.toFixed(2)+'s · '+VXT.formatDate(r.first.date):'—',r.latest?r.latest.time.toFixed(2)+'s · '+VXT.formatDate(r.latest.date):'—',r.improvement===null?'—':(r.improvement>=0?'+':'')+r.improvement.toFixed(2)+'s'])));
 body.append(node('p','Progress compares the best recorded time on the first and latest exact dates within each timing method. Positive improvement means faster. Season-only results count toward personal bests but not dated trends. Conditions may differ.'));
 const assignments=(d.teamWorkouts||[]).filter(w=>w.assignments.some(a=>a.athleteId===id)).sort((a,b)=>b.date.localeCompare(a.date));const completed=assignments.filter(w=>w.assignments.find(a=>a.athleteId===id).completed).length;body.append(node('h3','Training & attendance'),node('p',assignments.length+' assigned workouts · '+completed+' marked complete'));
 if(assignments.length)body.append(table(['Date / workout','Attendance','Target','Energy / soreness'],assignments.slice(0,20).map(w=>{const a=w.assignments.find(a=>a.athleteId===id);return [VXT.formatDate(w.date)+' · '+w.name,a.attendance||'Unrecorded',a.target||'—',(a.energy??'—')+'/5 · '+(a.soreness??'—')+'/10'];})));
 body.append(node('p','Most recent 20 assigned workouts shown. Unrecorded attendance is not counted as absent. Energy and soreness are athlete-reported, not a clinical assessment.'),node('h3','Coach notes / next priorities'));const notes=node('p',d.athleteReports?.find(r=>r.athleteId===id)?.notes||'No coach notes saved.');notes.style.whiteSpace='pre-wrap';body.append(notes);status('report-status','');});}
 el('report-athlete').addEventListener('change',()=>report(true));el('report-save').addEventListener('click',()=>run('report-status',()=>{VXTLocal.appendReviewed(VXTCoaching.saveReportNotes(VXTLocal.snapshot(),el('report-athlete').value,el('report-notes').value));report();status('report-status','Coach notes saved.');}));
 el('report-print').addEventListener('click',()=>{report();if(el('report-athlete').value)window.print();});
 el('report-download').addEventListener('click',()=>{report();if(!el('report-athlete').value)return;const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VXT Athlete Report</title><style>body{font:15px system-ui;color:#183830;max-width:1100px;margin:32px auto;padding:20px}table{border-collapse:collapse;width:100%;font-size:12px}td,th{border:1px solid #ccd5cc;padding:9px;text-align:left;overflow-wrap:anywhere}p{line-height:1.6}h2{font-size:28px}@media print{body{margin:0}tr{break-inside:avoid}}</style><body>'+el('report-content').innerHTML+'</body></html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));const a=node('a');a.href=url;a.download='VXT-athlete-report-'+today()+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('report-status','Report download started. It contains the selected athlete’s results and readiness data.');});
 document.querySelector('[data-tab="groups"]').addEventListener('click',()=>run('group-status',()=>{checkRoster('group-athletes',checked('group-athletes'));groups();}));document.querySelector('[data-tab="templates"]').addEventListener('click',()=>run('template-status',templates));document.querySelector('[data-tab="calendar"]').addEventListener('click',calendar);document.querySelector('[data-tab="reports"]').addEventListener('click',()=>report(true));for(const tab of ['team','blocks'])document.querySelector('[data-tab="'+tab+'"]').addEventListener('click',()=>run(tab==='team'?'team-status':'block-status',selectors));
 try{selectors();checkRoster('group-athletes');}catch(e){status('group-status',e.message);}
})();
