'use strict';
(()=>{
 const el=id=>document.getElementById(id),node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},button=(text,fn)=>{const b=node('button',text);b.type='button';b.addEventListener('click',fn);return b;};
 const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
 let store;try{store=VXTUXModel.draftStore(localStorage);}catch{}let restoring=false,undoing=false,undo=null;
 const editors=globalThis.VXTEditors||{},states=new Map();
 const draftMessage=(name,text)=>{const s=states.get(name);if(s)s.note.textContent=text;};
 function saveDraft(name){if(restoring)return;const editor=editors[name];if(!editor)return;try{if(!store)throw Error('Browser storage is unavailable. Keep this page open.');store.write(name,editor.capture());draftMessage(name,'Draft saved on this device · '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}));}catch(e){draftMessage(name,'Draft NOT saved: '+e.message);}}
 function clearDraft(name){try{store?.clear(name);draftMessage(name,'No unfinished draft.');}catch(e){draftMessage(name,e.message);}}
 function discardPrompt(parent,action){const box=node('div');box.hidden=true;box.append(node('p','Discard this unfinished draft? Saved sessions and results will stay.'),button('Discard draft',()=>{action();box.hidden=true;}),button('Keep draft',()=>box.hidden=true));parent.append(button('Discard draft…',()=>box.hidden=false),box);}
 function registerDrafts(){for(const [name,editor] of Object.entries(editors)){
  const form=el(editor.form),area=node('div');area.className='draft-bar';area.dataset.uxIgnore='true';const note=node('p','Changes save as a draft on this device.');note.setAttribute('role','status');area.append(note);form.after(area);states.set(name,{note});discardPrompt(area,()=>{restoring=true;try{editor.discard();store?.clear(name);note.textContent='Draft discarded.';}catch(e){note.textContent=e.message;}finally{restoring=false;}});
  form.addEventListener('input',()=>saveDraft(name));form.addEventListener('change',()=>saveDraft(name));form.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&b.type==='button'&&!/cancel|back|next/.test(b.id)&&!b.closest('[data-ux-ignore]'))queueMicrotask(()=>saveDraft(name));});
  try{const d=store?.read(name);if(d){restoring=true;editor.restore(d);note.textContent='Unfinished draft restored on this device.';}}catch(e){note.textContent='Draft could not be restored: '+e.message;}finally{restoring=false;}
 }}
 document.addEventListener('vxt-draft-change',e=>saveDraft(e.detail));document.addEventListener('vxt-clear-draft',e=>{clearDraft(e.detail);if(e.detail==='team'){targetValues={};el('team-targets').replaceChildren();setStep(1);}});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.textContent.startsWith('Edit '))queueMicrotask(()=>{for(const [name,editor] of Object.entries(editors))if(!el(editor.form).closest('.pane').hidden)saveDraft(name);});});
 function showUndo(){el('undo-bar').hidden=!undo;el('undo-label').textContent='Last deletion saved for undo on this device.';}
 function recordCommit(before,after){
  el('save-indicator').textContent='Records saved on this device at '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+' · cloud upload is manual';
  if(!undoing&&VXTUXModel.hasDeletion(before,after)){undo={before,after};try{localStorage.setItem('vxt-last-deletion-v1',JSON.stringify(undo));el('undo-status').textContent='';}catch{el('undo-status').textContent='Undo available until this page closes; storage is full.';}showUndo();}
 }
 try{const raw=localStorage.getItem('vxt-last-deletion-v1');if(raw){const parsed=JSON.parse(raw);VXT.validateData(parsed.before);VXT.validateData(parsed.after);undo=parsed;}}catch{el('undo-status').textContent='Previous undo copy could not be read.';}showUndo();
 el('undo-delete').addEventListener('click',()=>{try{if(!undo)return;const next=VXT.validateData(VXTUXModel.undoDeletion(undo.before,undo.after,VXTLocal.snapshot()));undoing=true;VXTLocal.appendReviewed(next);undo=null;localStorage.removeItem('vxt-last-deletion-v1');showUndo();const pane=document.querySelector('.pane:not([hidden])');document.querySelector('[data-tab="'+pane.id+'"]')?.click();el('save-indicator').textContent='Deletion undone. Records restored on this device.';}catch(e){el('undo-status').textContent=e.message;}finally{undoing=false;}});
 el('undo-dismiss').addEventListener('click',()=>{undo=null;try{localStorage.removeItem('vxt-last-deletion-v1');}catch{}showUndo();});
 document.addEventListener('vxt-workspace-replaced',()=>{try{for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith('vxt-draft-v1:'))localStorage.removeItem(key);}localStorage.removeItem('vxt-last-deletion-v1');}catch{}undo=null;showUndo();restoring=true;for(const [name,editor] of Object.entries(editors)){try{editor.discard();draftMessage(name,'Draft cleared after replacing workspace.');}catch{}}restoring=false;practiceState=null;practiceRender();});
 function openRecord(type,id){const pane={workouts:'team',sessions:'sessions',blocks:'blocks'}[type];document.querySelector('[data-tab="'+pane+'"]').click();const container=el({workouts:'team-history',sessions:'session-history',blocks:'block-history'}[type]);const field={workouts:'workoutId',sessions:'sessionId',blocks:'blockId'}[type];const section=[...container.children].find(x=>x.dataset[field]===id);if(section){section.open=true;section.scrollIntoView({block:'center'});}}
 function conflictActions(parent,c,skip){const row=node('div');row.className='conflict-actions';row.append(button('Skip athlete',skip));for(const type of ['blocks','workouts','sessions'])for(const record of c[type]||[])row.append(button('Open '+record.name,()=>openRecord(type,record.id)));parent.append(row);}
 // Guided workout form: retain existing controls and validation handlers.
 const form=el('team-form'),steps=[1,2,3].map(n=>{const section=node('section');section.className='wizard-step';section.dataset.wizardStep=n;return section;});let step=1,targetValues={};
 const templateRow=el('team-template').closest('.fields'),templateHint=templateRow.nextElementSibling;steps[0].append(templateRow,templateHint);
 for(const id of ['team-name','team-workout'])steps[0].append(el(id).closest('label'));
 steps[0].append(el('team-event').closest('fieldset'));const optional=node('details');optional.className='optional-fields';optional.append(node('summary','Optional workout notes'),el('team-notes').closest('label'));steps[0].append(optional);
 steps[1].append(el('team-athletes').closest('fieldset'));
 for(const id of ['team-date','team-start-time'])steps[2].append(el(id).closest('label'));steps[2].append(el('team-targets'),el('team-conflicts'));
 for(const section of steps)form.insertBefore(section,form.querySelector('.wizard-actions'));
 function targets(){for(const input of el('team-targets').querySelectorAll('input'))targetValues[input.dataset.athleteId]=input.value;return {...targetValues};}
 function renderTargets(){targets();const d=VXTLocal.snapshot();el('team-targets').replaceChildren();el('team-targets').append(node('h3','Individual targets (optional)'));for(const check of el('team-athletes').querySelectorAll('input:checked')){const name=d.athletes.find(a=>a.id===check.value)?.name;if(!name)continue;const label=node('label',name+' — target times / instructions'),input=node('input');input.dataset.athleteId=check.value;input.maxLength=500;input.value=targetValues[check.value]||'';input.placeholder='Example: 150m in 21–22 seconds';label.append(input);el('team-targets').append(label);}}
 function restoreTargets(value){targetValues={...value};el('team-targets').replaceChildren();renderTargets();}
 function setStep(n){step=n;steps.forEach((section,i)=>section.hidden=i+1!==n);el('team-back').hidden=n===1;el('team-next').hidden=n===3;el('team-save').hidden=n!==3;for(const b of el('team-steps').querySelectorAll('button')){const active=Number(b.dataset.step)===n;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'step':'false');}if(n===3)renderTargets();}
 function advance(){if(step===1&&(!el('team-name').value.trim()||!el('team-workout').value.trim())){el('team-status').textContent='Enter a workout name and prescription before choosing athletes.';return;}if(step===2&&!el('team-athletes').querySelector('input:checked')){el('team-status').textContent='Choose at least one athlete or group.';return;}setStep(Math.min(3,step+1));}
 el('team-next').addEventListener('click',advance);el('team-back').addEventListener('click',()=>setStep(Math.max(1,step-1)));for(const b of el('team-steps').querySelectorAll('button'))b.addEventListener('click',()=>{const n=Number(b.dataset.step);if(n<=step)setStep(n);else advance();});
 form.addEventListener('submit',e=>{if(step<3){e.preventDefault();e.stopImmediatePropagation();advance();}},true);document.addEventListener('vxt-use-template',()=>setStep(1));setStep(1);
 globalThis.VXTUX={recordCommit,targets,restoreTargets,conflictActions};
 for(const b of document.querySelectorAll('[data-main]:not([data-tab])'))b.addEventListener('click',()=>document.querySelector('[data-tab="'+{athletes:'dashboard',training:'team',reports:'reports'}[b.dataset.main]+'"]').click());
 el('today-plan').addEventListener('click',()=>document.querySelector('[data-tab="team"]').click());el('today-review').addEventListener('click',()=>document.querySelector('[data-tab="sessions"]').click());el('today-practice').addEventListener('click',()=>document.querySelector('[data-tab="practice"]').click());
 function todaySummary(){const d=VXTLocal.snapshot(),workouts=(d.teamWorkouts||[]).filter(w=>w.date===today());el('today-summary').textContent=VXT.formatDate(today())+' · '+workouts.length+' planned workout'+(workouts.length===1?'':'s')+' today';}
 document.querySelector('[data-tab="calendar"]').addEventListener('click',todaySummary);
 // Practice mode stores times as a per-workout draft; only finishing creates performance records.
 let practiceState=null;const practiceKey=id=>'practice:'+id;
 function practiceSave(){if(!practiceState)return;try{if(!store)throw Error('Storage unavailable');store.write(practiceKey(practiceState.workoutId),practiceState);el('practice-draft-status').textContent='Practice draft saved on this device · '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}catch(e){el('practice-draft-status').textContent='Draft NOT saved: '+e.message;}practiceSummary();}
 function practiceSummary(){const count=Object.values(practiceState?.times||{}).filter(v=>String(v).trim()!=='').length;el('practice-summary').textContent=count+' timed reps entered. Blank reps are omitted. Athletes with saved times are marked complete.';}
 function practiceSelect(){const d=VXTLocal.snapshot(),chosen=el('practice-workout').value;el('practice-workout').replaceChildren();const empty=node('option','Choose workout');empty.value='';el('practice-workout').append(empty);for(const w of [...d.teamWorkouts||[]].sort((a,b)=>b.date.localeCompare(a.date))){const o=node('option',VXT.formatDate(w.date)+' · '+VXT.formatStartTime(w.startTime)+' · '+w.name);o.value=w.id;el('practice-workout').append(o);}if(d.teamWorkouts?.some(w=>w.id===chosen))el('practice-workout').value=chosen;else{let last=null;try{last=store?.read('practice-selection')?.workoutId;}catch{}if(d.teamWorkouts?.some(w=>w.id===last))el('practice-workout').value=last;else el('practice-workout').value=d.teamWorkouts?.find(w=>w.date===today())?.id||'';}practiceLoad();}
 function practiceLoad(){const id=el('practice-workout').value;practiceState=null;el('practice-status').textContent='';el('practice-policy').value='';el('practice-draft-status').textContent='';if(id){try{practiceState=store?.read(practiceKey(id));if(practiceState&&(!practiceState.times||practiceState.workoutId!==id||typeof practiceState.times!=='object'))throw Error('Invalid practice draft.');if(practiceState)el('practice-draft-status').textContent='Practice draft restored on this device.';else practiceState={workoutId:id,signature:VXTUXModel.practiceSignature(VXTLocal.snapshot().teamWorkouts.find(w=>w.id===id)),times:{},method:'Gates'};store?.write('practice-selection',{workoutId:id});}catch(e){el('practice-draft-status').textContent='Draft could not be opened: '+e.message;practiceState=null;}}el('practice-method').value=practiceState?.method||'Gates';practiceRender();}
 function practiceRender(){const d=VXTLocal.snapshot(),w=d.teamWorkouts?.find(w=>w.id===el('practice-workout').value);el('practice-grid').replaceChildren();el('practice-conflicts').replaceChildren();el('practice-policy-label').hidden=true;el('practice-finish').disabled=!practiceState;el('practice-detailed').disabled=!w;if(!w){el('practice-prescription').textContent='Choose a planned workout, or use Plan workout on Today.';return;}
  el('practice-prescription').textContent=w.workout;const event=w.prescription?.event||'60m',count=w.prescription?.reps||1,race=VXTSessions.raceEvents.includes(event);el('practice-finish').hidden=!race;
  if(!race)el('practice-grid').append(node('p','Take attendance here, then open the detailed session log for '+event+' distances, segments and drill settings. That log also saves an unfinished draft.'));
  const table=node('table'),thead=node('thead'),head=node('tr');for(const text of ['Athlete / target','Attendance',...(race?Array.from({length:count},(_,i)=>'Rep '+(i+1)+' · '+event):[])])head.append(node('th',text));thead.append(head);table.append(thead);const body=node('tbody');const done=new Set((d.sessions||[]).filter(s=>s.sourceWorkoutId===w.id).flatMap(s=>s.efforts.map(e=>e.athleteId)));
  for(const a of w.assignments){const name=d.athletes.find(x=>x.id===a.athleteId)?.name||'Athlete',row=node('tr'),athlete=node('td');athlete.append(node('strong',name));if(a.target)athlete.append(node('p',a.target));if(done.has(a.athleteId))athlete.append(node('p','Results saved'));row.append(athlete);const cell=node('td'),attendance=node('select');attendance.setAttribute('aria-label','Practice attendance — '+name);for(const v of ['Unrecorded','Present','Absent','Modified']){const o=node('option',v);o.value=v;attendance.append(o);}attendance.value=a.attendance||'Unrecorded';attendance.addEventListener('change',()=>{try{const current=VXTLocal.snapshot().teamWorkouts.find(x=>x.id===w.id)?.assignments.find(x=>x.athleteId===a.athleteId);VXTLocal.appendReviewed(VXTCoaching.saveCheckin(VXTLocal.snapshot(),w.id,a.athleteId,{...current,attendance:attendance.value}));practiceSave();practiceRender();}catch(e){attendance.value=a.attendance||'Unrecorded';el('practice-status').textContent=e.message;}});cell.append(attendance);row.append(cell);
   if(race)for(let rep=0;rep<count;rep++){const td=node('td'),input=node('input');input.type='number';input.inputMode='decimal';input.step='0.01';input.min='0.01';input.max='3600';input.placeholder='Seconds';input.setAttribute('aria-label',name+' rep '+(rep+1)+' time');input.value=practiceState?.times[a.athleteId+':'+rep]||'';input.disabled=!practiceState||a.attendance==='Absent'||done.has(a.athleteId);input.addEventListener('input',()=>{practiceState.times[a.athleteId+':'+rep]=input.value;practiceSave();});td.append(input);row.append(td);}body.append(row);
  }table.append(body);el('practice-grid').append(table);
  const overlaps=VXT.schedulingConflicts(d,{date:w.date,excludeTeamId:w.id,athleteIds:w.assignments.filter(a=>a.attendance!=='Absent'&&!done.has(a.athleteId)).map(a=>a.athleteId)});el('practice-policy-label').hidden=!overlaps.length;
  if(overlaps.length){el('practice-conflicts').append(node('h3','Other assignments to review'));for(const c of overlaps){const p=node('div');p.className='practice-conflict';p.append(node('p',(d.athletes.find(a=>a.id===c.athleteId)?.name||'Athlete')+': '+[...c.blocks,...c.workouts,...c.sessions].map(x=>x.name).join(', ')));conflictActions(p,c,()=>{if(!practiceState)return;for(let rep=0;rep<count;rep++)delete practiceState.times[c.athleteId+':'+rep];practiceSave();el('practice-status').textContent='Timed entries removed for this athlete. Their assignment is unchanged.';practiceRender();});el('practice-conflicts').append(p);}}
  practiceSummary();
 }
 document.addEventListener('vxt-start-practice',e=>{document.querySelector('[data-tab="practice"]').click();el('practice-workout').value=e.detail;practiceLoad();});
 el('practice-workout').addEventListener('change',practiceLoad);el('practice-method').addEventListener('change',()=>{if(practiceState){practiceState.method=el('practice-method').value;practiceSave();}});document.querySelector('[data-tab="practice"]').addEventListener('click',practiceSelect);
 el('practice-finish').addEventListener('click',()=>{try{if(!practiceState)throw Error('Choose a workout with a readable draft.');const d=VXTLocal.snapshot(),w=d.teamWorkouts?.find(w=>w.id===practiceState.workoutId);if(!w)throw Error('Workout no longer exists.');if(w.date>today())throw Error('Save measured results on or after the workout date.');const reps=VXTUXModel.practiceEntries(d,w,practiceState);const r=VXTSessions.build(d,{name:w.name,date:w.date,startTime:w.startTime,notes:'Recorded in Practice mode.',method:practiceState.method,sourceWorkoutId:w.id,conflictPolicy:el('practice-policy').value},reps,()=>crypto.randomUUID());VXTLocal.appendReviewed(r.data);const savedIds=new Set(r.data.sessions.find(s=>s.id===r.sessionId).efforts.map(e=>e.athleteId));for(const key of Object.keys(practiceState.times))if(savedIds.has(key.slice(0,key.lastIndexOf(':'))))delete practiceState.times[key];if(Object.values(practiceState.times).some(v=>String(v).trim()!==''))practiceSave();else{store?.clear(practiceKey(w.id));el('practice-draft-status').textContent='Results saved. No unfinished timed entries.';}practiceRender();el('practice-status').textContent=r.records+' results saved for '+r.athletes+' athletes.'+(r.skipped?' '+r.skipped+' conflicting athletes skipped.':'');}catch(e){el('practice-status').textContent=e.message;}});
 el('practice-detailed').addEventListener('click',()=>{const id=el('practice-workout').value;if(id){openRecord('workouts',id);document.dispatchEvent(new CustomEvent('vxt-log-workout',{detail:id}));}});
 const practiceDiscard=node('div');el('practice-draft-status').after(practiceDiscard);discardPrompt(practiceDiscard,()=>{try{const id=el('practice-workout').value;if(id){store?.clear(practiceKey(id));practiceLoad();el('practice-draft-status').textContent='Practice draft discarded.';}}catch(e){el('practice-draft-status').textContent=e.message;}});
 document.addEventListener('vxt-tab',e=>{if(e.detail==='calendar')todaySummary();});
 registerDrafts();document.querySelector('[data-tab="calendar"]').click();
})();
